# Copyright 2026 ONCRIX Contributors
# SPDX-License-Identifier: Apache-2.0

[package]
name = "oncrix-test"
description = "ONCRIX - /bin/test utility (also linked as /bin/[)"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[[bin]]
name = "test"
path = "src/main.rs"

[dependencies]
oncrix-ulibc.workspace = true
