[package]
name = "oncrix-newgrp"
description = "ONCRIX - /bin/newgrp utility"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[[bin]]
name = "newgrp"
path = "src/main.rs"

[dependencies]
oncrix-ulibc.workspace = true
