[package]
name = "oncrix-fold"
description = "ONCRIX - /bin/fold utility"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[[bin]]
name = "fold"
path = "src/main.rs"

[dependencies]
oncrix-ulibc.workspace = true
