[package]
name = "oncrix-true"
description = "ONCRIX - /bin/true utility"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[[bin]]
name = "true"
path = "src/main.rs"

[dependencies]
oncrix-ulibc.workspace = true
