[package]
name = "oncrix-cat"
description = "ONCRIX - /bin/cat utility"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[[bin]]
name = "cat"
path = "src/main.rs"

[dependencies]
oncrix-ulibc.workspace = true
