[package]
name = "oncrix-init"
description = "ONCRIX - PID 1 init process"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[[bin]]
name = "init"
path = "src/main.rs"

[dependencies]
oncrix-ulibc.workspace = true
