[package]
name = "oncrix-unexpand"
description = "ONCRIX - /bin/unexpand utility"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[[bin]]
name = "unexpand"
path = "src/main.rs"

[dependencies]
oncrix-ulibc.workspace = true
