# Copyright 2026 ONCRIX Contributors
# SPDX-License-Identifier: Apache-2.0

[package]
name = "oncrix-install"
description = "ONCRIX - /bin/install utility"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[[bin]]
name = "install"
path = "src/main.rs"

[dependencies]
oncrix-ulibc.workspace = true
