[package]
name = "oncrix-chacl"
description = "ONCRIX - /bin/chacl utility"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[[bin]]
name = "chacl"
path = "src/main.rs"

[dependencies]
oncrix-ulibc.workspace = true
