[package]
name = "oncrix-pidstat"
description = "ONCRIX - /bin/pidstat utility"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[[bin]]
name = "pidstat"
path = "src/main.rs"

[dependencies]
oncrix-ulibc.workspace = true
