[package]
name = "oncrix-wall"
description = "ONCRIX - /bin/wall utility"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[[bin]]
name = "wall"
path = "src/main.rs"

[dependencies]
oncrix-ulibc.workspace = true
