[package]
name = "oncrix-md5sum"
description = "ONCRIX - /bin/md5sum utility"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[[bin]]
name = "md5sum"
path = "src/main.rs"

[dependencies]
oncrix-ulibc.workspace = true
