[package]
name = "oncrix-netstat"
description = "ONCRIX - /bin/netstat utility"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[[bin]]
name = "netstat"
path = "src/main.rs"

[dependencies]
oncrix-ulibc.workspace = true
