[package]
name = "oncrix-lsusb"
description = "ONCRIX - /bin/lsusb utility"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[[bin]]
name = "lsusb"
path = "src/main.rs"

[dependencies]
oncrix-ulibc.workspace = true
