[package]
name = "oncrix-batch"
description = "ONCRIX - /bin/batch utility"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[[bin]]
name = "batch"
path = "src/main.rs"

[dependencies]
oncrix-ulibc.workspace = true
