[package]
name = "oncrix-setfacl"
description = "ONCRIX - /bin/setfacl utility"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[[bin]]
name = "setfacl"
path = "src/main.rs"

[dependencies]
oncrix-ulibc.workspace = true
