[package]
name = "oncrix-sha512sum"
description = "ONCRIX - /bin/sha512sum utility"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[[bin]]
name = "sha512sum"
path = "src/main.rs"

[dependencies]
oncrix-ulibc.workspace = true
