[package]
name = "oncrix-rmdir"
description = "ONCRIX - /bin/rmdir utility"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[[bin]]
name = "rmdir"
path = "src/main.rs"

[dependencies]
oncrix-ulibc.workspace = true
