[package]
name = "oncrix-chmod"
description = "ONCRIX - /bin/chmod utility"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[[bin]]
name = "chmod"
path = "src/main.rs"

[dependencies]
oncrix-ulibc.workspace = true
