[package]
name = "oncrix-tabs"
description = "ONCRIX - /bin/tabs utility"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[[bin]]
name = "tabs"
path = "src/main.rs"

[dependencies]
oncrix-ulibc.workspace = true
