[package]
name = "oncrix-base32"
description = "ONCRIX - /bin/base32 utility"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[[bin]]
name = "base32"
path = "src/main.rs"

[dependencies]
oncrix-ulibc.workspace = true
