// Copyright 2026 ONCRIX Contributors
// SPDX-License-Identifier: Apache-2.0

//! Cgroup network classification controllers: `net_cls` and `net_prio`.
//!
//! # net_cls Controller
//!
//! The `net_cls` controller tags packets generated by processes in a cgroup
//! with a traffic control (tc) class identifier (`classid`). The kernel
//! attaches the classid to each packet's socket buffer, allowing `tc` (traffic
//! control) to classify and schedule them without per-packet matching overhead.
//!
//! Each classid is a 32-bit value encoded as `MMMM:mmmm` (major:minor) where:
//! - `major` (upper 16 bits) — tc qdisc handle.
//! - `minor` (lower 16 bits) — class within the qdisc.
//!
//! # net_prio Controller
//!
//! The `net_prio` controller maintains a per-network-interface priority map.
//! Packets from a cgroup are assigned a scheduling priority (0-7) per
//! interface before being handed to the network device queue. This maps
//! directly to the socket's `sk_priority` field.
//!
//! # Types
//!
//! - [`ClassId`] — tc class identifier (32-bit major:minor).
//! - [`NetClsController`] — single net_cls cgroup instance.
//! - [`NetPrioEntry`] — interface name + priority pair.
//! - [`NetPrioController`] — single net_prio cgroup instance.
//! - [`NetClsRegistry`] — system-wide net_cls registry.
//! - [`NetPrioRegistry`] — system-wide net_prio registry.
//! - [`NetCgroupRegistry`] — combined registry managing both controllers.
//!
//! # Reference
//!
//! Linux kernel `net/core/netclassid_cgroup.c`, `net/core/netprio_cgroup.c`,
//! `Documentation/admin-guide/cgroup-v1/net_cls.rst`,
//! `Documentation/admin-guide/cgroup-v1/net_prio.rst`.

use oncrix_lib::{Error, Result};

// ── Constants ─────────────────────────────────────────────────────────────────

/// Maximum number of net_cls cgroup controllers in the system.
const MAX_NET_CLS_CGROUPS: usize = 64;

/// Maximum number of net_prio cgroup controllers in the system.
const MAX_NET_PRIO_CGROUPS: usize = 64;

/// Maximum number of PIDs attached to a single network cgroup.
const MAX_PIDS_PER_GROUP: usize = 64;

/// Maximum number of interface priority entries per net_prio controller.
const MAX_IFPRIO_ENTRIES: usize = 16;

/// Maximum cgroup / interface name length in bytes.
const MAX_NAME_LEN: usize = 64;

/// Default classid (0 = unclassified, pass-through).
const DEFAULT_CLASSID: u32 = 0;

/// Maximum tc class priority (0 = highest, 7 = lowest for standard queues).
const MAX_PRIORITY: u8 = 7;

/// Mask for the major component of a classid (upper 16 bits).
const CLASSID_MAJOR_MASK: u32 = 0xFFFF_0000;

/// Mask for the minor component of a classid (lower 16 bits).
const CLASSID_MINOR_MASK: u32 = 0x0000_FFFF;

// ── ClassId ───────────────────────────────────────────────────────────────────

/// Traffic control class identifier, encoded as `major:minor` (each 16 bits).
///
/// A value of `0` (both major and minor zero) means unclassified — the packet
/// traverses the default tc qdisc without special classification.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct ClassId(pub u32);

impl ClassId {
    /// Create a `ClassId` from separate major and minor handles.
    pub const fn from_parts(major: u16, minor: u16) -> Self {
        Self(((major as u32) << 16) | (minor as u32))
    }

    /// Return the major handle (upper 16 bits).
    pub fn major(self) -> u16 {
        ((self.0 & CLASSID_MAJOR_MASK) >> 16) as u16
    }

    /// Return the minor handle (lower 16 bits).
    pub fn minor(self) -> u16 {
        (self.0 & CLASSID_MINOR_MASK) as u16
    }

    /// Return `true` if this classid represents the unclassified default.
    pub fn is_unclassified(self) -> bool {
        self.0 == 0
    }
}

impl core::fmt::Display for ClassId {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, "{:04x}:{:04x}", self.major(), self.minor())
    }
}

// ── NetClsStats ───────────────────────────────────────────────────────────────

/// Statistics for a `net_cls` controller.
#[derive(Debug, Clone, Copy, Default)]
pub struct NetClsStats {
    /// Total packets classified by this controller.
    pub packets_classified: u64,
    /// Total packets that passed through unclassified (classid == 0).
    pub packets_unclassified: u64,
}

// ── NetClsController ─────────────────────────────────────────────────────────

/// A single `net_cls` cgroup controller instance.
///
/// Associates a cgroup (identified by `id`) with a tc classid. All packets
/// originating from processes in the cgroup receive this classid tag.
#[derive(Clone, Copy)]
pub struct NetClsController {
    /// Unique controller identifier.
    pub id: u64,
    /// Human-readable name (e.g., the cgroup path component).
    name: [u8; MAX_NAME_LEN],
    /// Length of the valid name bytes.
    name_len: usize,
    /// Traffic control classid assigned to this cgroup.
    pub classid: ClassId,
    /// Attached process IDs.
    pids: [u64; MAX_PIDS_PER_GROUP],
    /// Number of attached PIDs.
    pid_count: usize,
    /// Statistics.
    pub stats: NetClsStats,
    /// Whether this controller is active.
    pub active: bool,
}

impl Default for NetClsController {
    fn default() -> Self {
        Self {
            id: 0,
            name: [0u8; MAX_NAME_LEN],
            name_len: 0,
            classid: ClassId(DEFAULT_CLASSID),
            pids: [0u64; MAX_PIDS_PER_GROUP],
            pid_count: 0,
            stats: NetClsStats::default(),
            active: false,
        }
    }
}

impl NetClsController {
    /// Create a new, active controller with the given `id` and `name`.
    pub fn new(id: u64, name: &[u8]) -> Self {
        let mut ctrl = Self::default();
        ctrl.id = id;
        ctrl.active = true;
        let copy_len = name.len().min(MAX_NAME_LEN);
        ctrl.name[..copy_len].copy_from_slice(&name[..copy_len]);
        ctrl.name_len = copy_len;
        ctrl
    }

    /// Return the controller name as a byte slice.
    pub fn name(&self) -> &[u8] {
        &self.name[..self.name_len]
    }

    /// Set the tc classid for this cgroup.
    pub fn set_classid(&mut self, classid: ClassId) {
        self.classid = classid;
    }

    /// Attach a PID to this controller.
    ///
    /// # Errors
    ///
    /// - [`Error::OutOfMemory`] if the PID table is full.
    /// - [`Error::AlreadyExists`] if the PID is already attached.
    pub fn attach_pid(&mut self, pid: u64) -> Result<()> {
        // Deduplication.
        if self.pids[..self.pid_count].contains(&pid) {
            return Err(Error::AlreadyExists);
        }
        if self.pid_count >= MAX_PIDS_PER_GROUP {
            return Err(Error::OutOfMemory);
        }
        self.pids[self.pid_count] = pid;
        self.pid_count += 1;
        Ok(())
    }

    /// Detach a PID from this controller.
    ///
    /// # Errors
    ///
    /// - [`Error::NotFound`] if the PID is not attached.
    pub fn detach_pid(&mut self, pid: u64) -> Result<()> {
        let pos = self.pids[..self.pid_count].iter().position(|&p| p == pid);
        match pos {
            Some(idx) => {
                self.pids[idx] = self.pids[self.pid_count - 1];
                self.pid_count -= 1;
                Ok(())
            }
            None => Err(Error::NotFound),
        }
    }

    /// Return `true` if `pid` is attached to this controller.
    pub fn has_pid(&self, pid: u64) -> bool {
        self.pids[..self.pid_count].contains(&pid)
    }

    /// Look up the classid for a packet from `pid`.
    ///
    /// Updates internal statistics. Returns `ClassId(0)` if the PID is not
    /// in this controller.
    pub fn classify(&mut self, pid: u64) -> ClassId {
        if self.has_pid(pid) {
            if self.classid.is_unclassified() {
                self.stats.packets_unclassified += 1;
            } else {
                self.stats.packets_classified += 1;
            }
            self.classid
        } else {
            ClassId(0)
        }
    }

    /// Return a slice of attached PIDs.
    pub fn pids(&self) -> &[u64] {
        &self.pids[..self.pid_count]
    }
}

// ── NetPrioEntry ──────────────────────────────────────────────────────────────

/// Per-interface priority entry in a `net_prio` map.
#[derive(Clone, Copy)]
pub struct NetPrioEntry {
    /// Network interface name (e.g., `b"eth0"`), null-padded.
    ifname: [u8; MAX_NAME_LEN],
    /// Length of the valid interface name bytes.
    ifname_len: usize,
    /// Socket priority (0 = highest, 7 = lowest in standard POSIX/SO_PRIORITY).
    pub priority: u8,
    /// Whether this entry is occupied.
    pub active: bool,
}

impl Default for NetPrioEntry {
    fn default() -> Self {
        Self {
            ifname: [0u8; MAX_NAME_LEN],
            ifname_len: 0,
            priority: 0,
            active: false,
        }
    }
}

impl NetPrioEntry {
    /// Create a new entry for `ifname` with the given `priority`.
    ///
    /// # Errors
    ///
    /// - [`Error::InvalidArgument`] if `priority > MAX_PRIORITY`.
    pub fn new(ifname: &[u8], priority: u8) -> Result<Self> {
        if priority > MAX_PRIORITY {
            return Err(Error::InvalidArgument);
        }
        let mut entry = Self::default();
        let copy_len = ifname.len().min(MAX_NAME_LEN);
        entry.ifname[..copy_len].copy_from_slice(&ifname[..copy_len]);
        entry.ifname_len = copy_len;
        entry.priority = priority;
        entry.active = true;
        Ok(entry)
    }

    /// Return the interface name as a byte slice.
    pub fn ifname(&self) -> &[u8] {
        &self.ifname[..self.ifname_len]
    }
}

// ── NetPrioStats ─────────────────────────────────────────────────────────────

/// Statistics for a `net_prio` controller.
#[derive(Debug, Clone, Copy, Default)]
pub struct NetPrioStats {
    /// Total packets to which a priority was assigned.
    pub packets_prioritized: u64,
    /// Total packets that used the default priority (no match found).
    pub packets_default_priority: u64,
}

// ── NetPrioController ────────────────────────────────────────────────────────

/// A single `net_prio` cgroup controller instance.
///
/// Maintains a map of `(interface_name → priority)` pairs. When a packet from
/// a member process is queued for transmission, the kernel looks up the
/// interface name and sets `sk_priority` accordingly.
#[derive(Clone, Copy)]
pub struct NetPrioController {
    /// Unique controller identifier.
    pub id: u64,
    /// Human-readable name.
    name: [u8; MAX_NAME_LEN],
    /// Length of the valid name bytes.
    name_len: usize,
    /// Per-interface priority map.
    ifprio: [NetPrioEntry; MAX_IFPRIO_ENTRIES],
    /// Number of active entries in `ifprio`.
    ifprio_count: usize,
    /// Default priority for interfaces not in the map (0 = highest).
    pub default_priority: u8,
    /// Attached process IDs.
    pids: [u64; MAX_PIDS_PER_GROUP],
    /// Number of attached PIDs.
    pid_count: usize,
    /// Statistics.
    pub stats: NetPrioStats,
    /// Whether this controller is active.
    pub active: bool,
}

impl Default for NetPrioController {
    fn default() -> Self {
        Self {
            id: 0,
            name: [0u8; MAX_NAME_LEN],
            name_len: 0,
            ifprio: [NetPrioEntry::default(); MAX_IFPRIO_ENTRIES],
            ifprio_count: 0,
            default_priority: 0,
            pids: [0u64; MAX_PIDS_PER_GROUP],
            pid_count: 0,
            stats: NetPrioStats::default(),
            active: false,
        }
    }
}

impl NetPrioController {
    /// Create a new, active controller with the given `id` and `name`.
    pub fn new(id: u64, name: &[u8]) -> Self {
        let mut ctrl = Self::default();
        ctrl.id = id;
        ctrl.active = true;
        let copy_len = name.len().min(MAX_NAME_LEN);
        ctrl.name[..copy_len].copy_from_slice(&name[..copy_len]);
        ctrl.name_len = copy_len;
        ctrl
    }

    /// Return the controller name.
    pub fn name(&self) -> &[u8] {
        &self.name[..self.name_len]
    }

    /// Set the priority for a named interface.
    ///
    /// If an entry for `ifname` already exists, its priority is updated.
    /// Otherwise a new entry is created.
    ///
    /// # Errors
    ///
    /// - [`Error::InvalidArgument`] if `priority > MAX_PRIORITY`.
    /// - [`Error::OutOfMemory`] if the interface map is full.
    pub fn set_ifprio(&mut self, ifname: &[u8], priority: u8) -> Result<()> {
        if priority > MAX_PRIORITY {
            return Err(Error::InvalidArgument);
        }
        // Update existing entry.
        for i in 0..self.ifprio_count {
            if self.ifprio[i].active && self.ifprio[i].ifname() == ifname {
                self.ifprio[i].priority = priority;
                return Ok(());
            }
        }
        // Add new entry.
        if self.ifprio_count >= MAX_IFPRIO_ENTRIES {
            return Err(Error::OutOfMemory);
        }
        self.ifprio[self.ifprio_count] = NetPrioEntry::new(ifname, priority)?;
        self.ifprio_count += 1;
        Ok(())
    }

    /// Remove the priority entry for `ifname`.
    ///
    /// # Errors
    ///
    /// - [`Error::NotFound`] if no entry for `ifname` exists.
    pub fn clear_ifprio(&mut self, ifname: &[u8]) -> Result<()> {
        let pos = self.ifprio[..self.ifprio_count]
            .iter()
            .position(|e| e.active && e.ifname() == ifname);
        match pos {
            Some(idx) => {
                self.ifprio[idx] = self.ifprio[self.ifprio_count - 1];
                self.ifprio_count -= 1;
                Ok(())
            }
            None => Err(Error::NotFound),
        }
    }

    /// Look up the priority for a packet on `ifname` from `pid`.
    ///
    /// Returns the mapped priority if found, otherwise `self.default_priority`.
    /// Updates internal statistics.
    pub fn get_priority(&mut self, pid: u64, ifname: &[u8]) -> u8 {
        if !self.has_pid(pid) {
            return self.default_priority;
        }
        let prio = self.ifprio[..self.ifprio_count]
            .iter()
            .find(|e| e.active && e.ifname() == ifname)
            .map(|e| e.priority);
        match prio {
            Some(p) => {
                self.stats.packets_prioritized += 1;
                p
            }
            None => {
                self.stats.packets_default_priority += 1;
                self.default_priority
            }
        }
    }

    /// Return an immutable slice of active interface-priority entries.
    pub fn ifprio_map(&self) -> &[NetPrioEntry] {
        &self.ifprio[..self.ifprio_count]
    }

    /// Attach a PID to this controller.
    ///
    /// # Errors
    ///
    /// - [`Error::OutOfMemory`] if the PID table is full.
    /// - [`Error::AlreadyExists`] if the PID is already attached.
    pub fn attach_pid(&mut self, pid: u64) -> Result<()> {
        if self.pids[..self.pid_count].contains(&pid) {
            return Err(Error::AlreadyExists);
        }
        if self.pid_count >= MAX_PIDS_PER_GROUP {
            return Err(Error::OutOfMemory);
        }
        self.pids[self.pid_count] = pid;
        self.pid_count += 1;
        Ok(())
    }

    /// Detach a PID from this controller.
    ///
    /// # Errors
    ///
    /// - [`Error::NotFound`] if the PID is not attached.
    pub fn detach_pid(&mut self, pid: u64) -> Result<()> {
        let pos = self.pids[..self.pid_count].iter().position(|&p| p == pid);
        match pos {
            Some(idx) => {
                self.pids[idx] = self.pids[self.pid_count - 1];
                self.pid_count -= 1;
                Ok(())
            }
            None => Err(Error::NotFound),
        }
    }

    /// Return `true` if `pid` is attached to this controller.
    pub fn has_pid(&self, pid: u64) -> bool {
        self.pids[..self.pid_count].contains(&pid)
    }

    /// Return a slice of attached PIDs.
    pub fn pids(&self) -> &[u64] {
        &self.pids[..self.pid_count]
    }
}

// ── NetClsRegistry ────────────────────────────────────────────────────────────

/// System-wide registry of `net_cls` cgroup controllers.
pub struct NetClsRegistry {
    /// Controller array.
    controllers: [NetClsController; MAX_NET_CLS_CGROUPS],
    /// Number of active controllers.
    count: usize,
    /// Monotonic ID counter.
    next_id: u64,
}

impl NetClsRegistry {
    /// Create an empty registry.
    pub fn new() -> Self {
        Self {
            controllers: core::array::from_fn(|_| NetClsController::default()),
            count: 0,
            next_id: 1,
        }
    }

    /// Create a new net_cls controller with the given `name`.
    ///
    /// Returns the controller's unique ID.
    ///
    /// # Errors
    ///
    /// - [`Error::OutOfMemory`] if the registry is full.
    /// - [`Error::AlreadyExists`] if a controller with the same name exists.
    pub fn create(&mut self, name: &[u8]) -> Result<u64> {
        if self.count >= MAX_NET_CLS_CGROUPS {
            return Err(Error::OutOfMemory);
        }
        for c in &self.controllers[..self.count] {
            if c.active && c.name() == name {
                return Err(Error::AlreadyExists);
            }
        }
        let idx = self.count;
        let id = self.next_id;
        self.controllers[idx] = NetClsController::new(id, name);
        self.next_id += 1;
        self.count += 1;
        Ok(id)
    }

    /// Look up a controller by ID (immutable).
    ///
    /// # Errors
    ///
    /// - [`Error::NotFound`] if no active controller matches `id`.
    pub fn get(&self, id: u64) -> Result<&NetClsController> {
        self.controllers[..self.count]
            .iter()
            .find(|c| c.active && c.id == id)
            .ok_or(Error::NotFound)
    }

    /// Look up a controller by ID (mutable).
    ///
    /// # Errors
    ///
    /// - [`Error::NotFound`] if no active controller matches `id`.
    pub fn get_mut(&mut self, id: u64) -> Result<&mut NetClsController> {
        self.controllers[..self.count]
            .iter_mut()
            .find(|c| c.active && c.id == id)
            .ok_or(Error::NotFound)
    }

    /// Destroy the controller with the given `id`.
    ///
    /// # Errors
    ///
    /// - [`Error::NotFound`] if no active controller matches `id`.
    pub fn destroy(&mut self, id: u64) -> Result<()> {
        let pos = self.controllers[..self.count]
            .iter()
            .position(|c| c.active && c.id == id);
        match pos {
            Some(idx) => {
                self.controllers[idx].active = false;
                if idx + 1 < self.count {
                    self.controllers.swap(idx, self.count - 1);
                }
                self.count -= 1;
                Ok(())
            }
            None => Err(Error::NotFound),
        }
    }

    /// Classify a packet from `pid` by looking through all active controllers.
    ///
    /// Returns the first non-zero classid found, or `ClassId(0)` if the PID
    /// is not in any controller.
    pub fn classify_packet(&mut self, pid: u64) -> ClassId {
        for ctrl in &mut self.controllers[..self.count] {
            if ctrl.active {
                let cid = ctrl.classify(pid);
                if !cid.is_unclassified() {
                    return cid;
                }
            }
        }
        ClassId(0)
    }

    /// Return the number of active controllers.
    pub fn len(&self) -> usize {
        self.count
    }

    /// Return `true` if there are no active controllers.
    pub fn is_empty(&self) -> bool {
        self.count == 0
    }
}

impl Default for NetClsRegistry {
    fn default() -> Self {
        Self::new()
    }
}

// ── NetPrioRegistry ───────────────────────────────────────────────────────────

/// System-wide registry of `net_prio` cgroup controllers.
pub struct NetPrioRegistry {
    /// Controller array.
    controllers: [NetPrioController; MAX_NET_PRIO_CGROUPS],
    /// Number of active controllers.
    count: usize,
    /// Monotonic ID counter.
    next_id: u64,
}

impl NetPrioRegistry {
    /// Create an empty registry.
    pub fn new() -> Self {
        Self {
            controllers: core::array::from_fn(|_| NetPrioController::default()),
            count: 0,
            next_id: 1,
        }
    }

    /// Create a new net_prio controller with the given `name`.
    ///
    /// Returns the controller's unique ID.
    ///
    /// # Errors
    ///
    /// - [`Error::OutOfMemory`] if the registry is full.
    /// - [`Error::AlreadyExists`] if a controller with the same name exists.
    pub fn create(&mut self, name: &[u8]) -> Result<u64> {
        if self.count >= MAX_NET_PRIO_CGROUPS {
            return Err(Error::OutOfMemory);
        }
        for c in &self.controllers[..self.count] {
            if c.active && c.name() == name {
                return Err(Error::AlreadyExists);
            }
        }
        let idx = self.count;
        let id = self.next_id;
        self.controllers[idx] = NetPrioController::new(id, name);
        self.next_id += 1;
        self.count += 1;
        Ok(id)
    }

    /// Look up a controller by ID (immutable).
    ///
    /// # Errors
    ///
    /// - [`Error::NotFound`] if no active controller matches `id`.
    pub fn get(&self, id: u64) -> Result<&NetPrioController> {
        self.controllers[..self.count]
            .iter()
            .find(|c| c.active && c.id == id)
            .ok_or(Error::NotFound)
    }

    /// Look up a controller by ID (mutable).
    ///
    /// # Errors
    ///
    /// - [`Error::NotFound`] if no active controller matches `id`.
    pub fn get_mut(&mut self, id: u64) -> Result<&mut NetPrioController> {
        self.controllers[..self.count]
            .iter_mut()
            .find(|c| c.active && c.id == id)
            .ok_or(Error::NotFound)
    }

    /// Destroy the controller with the given `id`.
    ///
    /// # Errors
    ///
    /// - [`Error::NotFound`] if no active controller matches `id`.
    pub fn destroy(&mut self, id: u64) -> Result<()> {
        let pos = self.controllers[..self.count]
            .iter()
            .position(|c| c.active && c.id == id);
        match pos {
            Some(idx) => {
                self.controllers[idx].active = false;
                if idx + 1 < self.count {
                    self.controllers.swap(idx, self.count - 1);
                }
                self.count -= 1;
                Ok(())
            }
            None => Err(Error::NotFound),
        }
    }

    /// Resolve the priority for a packet from `pid` on `ifname`.
    ///
    /// Searches all active controllers for one that has `pid` attached,
    /// then returns its mapped priority for `ifname`. Returns
    /// `default_priority` (0) if no match is found.
    pub fn get_priority(&mut self, pid: u64, ifname: &[u8]) -> u8 {
        for ctrl in &mut self.controllers[..self.count] {
            if ctrl.active && ctrl.has_pid(pid) {
                return ctrl.get_priority(pid, ifname);
            }
        }
        0
    }

    /// Return the number of active controllers.
    pub fn len(&self) -> usize {
        self.count
    }

    /// Return `true` if there are no active controllers.
    pub fn is_empty(&self) -> bool {
        self.count == 0
    }
}

impl Default for NetPrioRegistry {
    fn default() -> Self {
        Self::new()
    }
}

// ── NetCgroupRegistry ─────────────────────────────────────────────────────────

/// Combined cgroup network controller registry.
///
/// Acts as the top-level entry point for both `net_cls` and `net_prio`
/// operations. The kernel's socket path calls into this type to annotate
/// packets before enqueueing them on the network device.
pub struct NetCgroupRegistry {
    /// `net_cls` classid registry.
    pub net_cls: NetClsRegistry,
    /// `net_prio` priority registry.
    pub net_prio: NetPrioRegistry,
}

impl NetCgroupRegistry {
    /// Create an empty combined registry.
    pub fn new() -> Self {
        Self {
            net_cls: NetClsRegistry::new(),
            net_prio: NetPrioRegistry::new(),
        }
    }

    /// Annotate a packet from `pid` destined for `ifname`.
    ///
    /// Fills in the `classid` and `priority` fields based on the cgroup
    /// controllers the PID belongs to.
    pub fn annotate(&mut self, pid: u64, ifname: &[u8]) -> PacketAnnotation {
        PacketAnnotation {
            classid: self.net_cls.classify_packet(pid),
            priority: self.net_prio.get_priority(pid, ifname),
        }
    }
}

impl Default for NetCgroupRegistry {
    fn default() -> Self {
        Self::new()
    }
}

// ── PacketAnnotation ──────────────────────────────────────────────────────────

/// Combined network classification annotation for a packet.
///
/// The kernel attaches this to the socket buffer before passing it to the
/// traffic control layer.
#[derive(Debug, Clone, Copy, Default)]
pub struct PacketAnnotation {
    /// tc classid for `net_cls` (0 = unclassified).
    pub classid: ClassId,
    /// Socket priority for `net_prio` (0 = highest, 7 = lowest).
    pub priority: u8,
}

impl PacketAnnotation {
    /// Return `true` if the packet should be treated as unclassified
    /// (no special tc class and default priority).
    pub fn is_default(&self) -> bool {
        self.classid.is_unclassified() && self.priority == 0
    }
}

// ── Unit tests ────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    // ── ClassId ──────────────────────────────────────────────────────────────

    #[test]
    fn classid_round_trip() {
        let cid = ClassId::from_parts(0x0001, 0x0010);
        assert_eq!(cid.major(), 0x0001);
        assert_eq!(cid.minor(), 0x0010);
    }

    #[test]
    fn classid_unclassified() {
        assert!(ClassId(0).is_unclassified());
        assert!(!ClassId::from_parts(1, 0).is_unclassified());
    }

    // ── NetClsController ─────────────────────────────────────────────────────

    #[test]
    fn net_cls_attach_detach_pid() {
        let mut ctrl = NetClsController::new(1, b"web");
        ctrl.attach_pid(100).expect("attach");
        assert!(ctrl.has_pid(100));
        ctrl.detach_pid(100).expect("detach");
        assert!(!ctrl.has_pid(100));
    }

    #[test]
    fn net_cls_classify_pid() {
        let mut ctrl = NetClsController::new(1, b"web");
        ctrl.set_classid(ClassId::from_parts(1, 10));
        ctrl.attach_pid(42).unwrap();
        let cid = ctrl.classify(42);
        assert_eq!(cid, ClassId::from_parts(1, 10));
        assert_eq!(ctrl.stats.packets_classified, 1);
    }

    #[test]
    fn net_cls_classify_unknown_pid_returns_zero() {
        let mut ctrl = NetClsController::new(1, b"web");
        ctrl.set_classid(ClassId::from_parts(1, 10));
        let cid = ctrl.classify(999);
        assert!(cid.is_unclassified());
    }

    // ── NetPrioController ────────────────────────────────────────────────────

    #[test]
    fn net_prio_set_ifprio() {
        let mut ctrl = NetPrioController::new(1, b"batch");
        ctrl.attach_pid(77).unwrap();
        ctrl.set_ifprio(b"eth0", 5).expect("set ifprio");
        assert_eq!(ctrl.get_priority(77, b"eth0"), 5);
    }

    #[test]
    fn net_prio_default_priority_on_unknown_iface() {
        let mut ctrl = NetPrioController::new(1, b"batch");
        ctrl.attach_pid(77).unwrap();
        ctrl.default_priority = 3;
        assert_eq!(ctrl.get_priority(77, b"wlan0"), 3);
    }

    #[test]
    fn net_prio_invalid_priority_rejected() {
        let mut ctrl = NetPrioController::new(1, b"batch");
        assert!(ctrl.set_ifprio(b"eth0", MAX_PRIORITY + 1).is_err());
    }

    #[test]
    fn net_prio_clear_ifprio() {
        let mut ctrl = NetPrioController::new(1, b"batch");
        ctrl.attach_pid(77).unwrap();
        ctrl.set_ifprio(b"eth0", 5).unwrap();
        ctrl.clear_ifprio(b"eth0").unwrap();
        assert_eq!(ctrl.get_priority(77, b"eth0"), ctrl.default_priority);
    }

    // ── NetClsRegistry ───────────────────────────────────────────────────────

    #[test]
    fn net_cls_registry_create_get_destroy() {
        let mut reg = NetClsRegistry::new();
        let id = reg.create(b"group1").expect("create");
        assert!(reg.get(id).is_ok());
        reg.destroy(id).expect("destroy");
        assert!(reg.get(id).is_err());
    }

    #[test]
    fn net_cls_registry_duplicate_name_rejected() {
        let mut reg = NetClsRegistry::new();
        reg.create(b"grp").unwrap();
        assert!(reg.create(b"grp").is_err());
    }

    // ── NetPrioRegistry ──────────────────────────────────────────────────────

    #[test]
    fn net_prio_registry_priority_lookup() {
        let mut reg = NetPrioRegistry::new();
        let id = reg.create(b"high").expect("create");
        let ctrl = reg.get_mut(id).unwrap();
        ctrl.attach_pid(55).unwrap();
        ctrl.set_ifprio(b"eth0", 2).unwrap();
        assert_eq!(reg.get_priority(55, b"eth0"), 2);
    }

    // ── NetCgroupRegistry ────────────────────────────────────────────────────

    #[test]
    fn combined_annotate() {
        let mut reg = NetCgroupRegistry::new();
        let cls_id = reg.net_cls.create(b"web").unwrap();
        {
            let ctrl = reg.net_cls.get_mut(cls_id).unwrap();
            ctrl.set_classid(ClassId::from_parts(1, 5));
            ctrl.attach_pid(10).unwrap();
        }
        let prio_id = reg.net_prio.create(b"web-prio").unwrap();
        {
            let ctrl = reg.net_prio.get_mut(prio_id).unwrap();
            ctrl.attach_pid(10).unwrap();
            ctrl.set_ifprio(b"eth0", 3).unwrap();
        }
        let ann = reg.annotate(10, b"eth0");
        assert_eq!(ann.classid, ClassId::from_parts(1, 5));
        assert_eq!(ann.priority, 3);
        assert!(!ann.is_default());
    }

    #[test]
    fn annotation_default_for_unknown_pid() {
        let mut reg = NetCgroupRegistry::new();
        let ann = reg.annotate(999, b"eth0");
        assert!(ann.is_default());
    }
}
