// Copyright 2026 ONCRIX Contributors
// SPDX-License-Identifier: Apache-2.0

//! Pending signal management.
//!
//! Manages the set of pending signals and queued siginfo entries for
//! a task or thread group. Provides operations to send, dequeue,
//! and flush signals, as well as query pending signal state.
//!
//! # Signal Sets
//!
//! ```text
//! ┌────────────────────────────────────────────────┐
//! │ sigset_t (u64 bitmask)                          │
//! │                                                 │
//! │ Bit 0  = Signal 1  (SIGHUP)                     │
//! │ Bit 1  = Signal 2  (SIGINT)                     │
//! │ Bit 2  = Signal 3  (SIGQUIT)                    │
//! │ ...                                             │
//! │ Bit 30 = Signal 31 (SIGSYS)                     │
//! │ Bits 31-63 = Real-time signals (SIGRTMIN+N)     │
//! └────────────────────────────────────────────────┘
//! ```
//!
//! # Queue Structure
//!
//! ```text
//! SigPending
//! ├── signal (sigset_t bitmask — which signals are pending)
//! └── queue[] (SigQueueEntry — detailed siginfo for each)
//!     ├── signo=2, code=SI_USER, pid=100, uid=1000
//!     ├── signo=14, code=SI_TIMER, ...
//!     └── signo=17, code=CLD_EXITED, pid=200, ...
//! ```
//!
//! # Reference
//!
//! Linux `kernel/signal.c`, `include/linux/signal.h`.

use oncrix_lib::{Error, Result};

// ======================================================================
// Constants
// ======================================================================

/// Maximum number of queued signal entries per task.
const MAX_SIGQUEUE: usize = 64;

/// Number of standard signals (1-31).
const _NUM_STD_SIGNALS: usize = 31;

/// Number of real-time signals (32-64).
const _NUM_RT_SIGNALS: usize = 33;

/// Total number of signals.
const NUM_SIGNALS: usize = 64;

/// Signal numbers (POSIX standard signals).
pub const SIGHUP: u8 = 1;
pub const SIGINT: u8 = 2;
pub const SIGQUIT: u8 = 3;
pub const SIGILL: u8 = 4;
pub const SIGTRAP: u8 = 5;
pub const SIGABRT: u8 = 6;
pub const SIGBUS: u8 = 7;
pub const SIGFPE: u8 = 8;
pub const SIGKILL: u8 = 9;
pub const SIGUSR1: u8 = 10;
pub const SIGSEGV: u8 = 11;
pub const SIGUSR2: u8 = 12;
pub const SIGPIPE: u8 = 13;
pub const SIGALRM: u8 = 14;
pub const SIGTERM: u8 = 15;
pub const SIGCHLD: u8 = 17;
pub const SIGCONT: u8 = 18;
pub const SIGSTOP: u8 = 19;
pub const SIGTSTP: u8 = 20;
pub const SIGTTIN: u8 = 21;
pub const SIGTTOU: u8 = 22;
pub const SIGURG: u8 = 23;
pub const SIGXCPU: u8 = 24;
pub const SIGXFSZ: u8 = 25;
pub const SIGVTALRM: u8 = 26;
pub const SIGPROF: u8 = 27;
pub const SIGWINCH: u8 = 28;
pub const SIGIO: u8 = 29;
pub const SIGSYS: u8 = 31;
pub const SIGRTMIN: u8 = 32;

/// Mask of signals that cannot be caught or ignored.
const UNCATCHABLE_MASK: u64 = (1u64 << (SIGKILL - 1)) | (1u64 << (SIGSTOP - 1));

// ======================================================================
// Signal info code
// ======================================================================

/// Signal info code (si_code).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SigCode {
    /// Sent by kill(), sigsend(), raise().
    User,
    /// Sent by the kernel.
    Kernel,
    /// Sent by a queued signal (sigqueue()).
    Queue,
    /// Sent by a timer expiration.
    Timer,
    /// Sent by a message queue state change.
    MsgQueue,
    /// Sent by async I/O completion.
    AsyncIo,
    /// Sent by signal generated by child exit.
    ChildExited,
    /// Sent by signal generated by child stopped.
    ChildStopped,
    /// Sent by signal generated by child continued.
    ChildContinued,
}

// ======================================================================
// Signal queue entry
// ======================================================================

/// A queued signal entry with extended information.
#[derive(Debug, Clone, Copy)]
pub struct SigQueueEntry {
    /// Signal number (1-64).
    signo: u8,
    /// Signal code.
    code: SigCode,
    /// Sending PID.
    sender_pid: u32,
    /// Sending UID.
    sender_uid: u32,
    /// Value (for sigqueue / timer signals).
    value: u64,
    /// Timestamp when the signal was sent (ns).
    timestamp_ns: u64,
    /// Whether this entry is occupied.
    occupied: bool,
}

impl SigQueueEntry {
    /// Creates an empty queue entry.
    pub const fn new() -> Self {
        Self {
            signo: 0,
            code: SigCode::User,
            sender_pid: 0,
            sender_uid: 0,
            value: 0,
            timestamp_ns: 0,
            occupied: false,
        }
    }

    /// Returns the signal number.
    pub fn signo(&self) -> u8 {
        self.signo
    }

    /// Returns the signal code.
    pub fn code(&self) -> SigCode {
        self.code
    }

    /// Returns the sender PID.
    pub fn sender_pid(&self) -> u32 {
        self.sender_pid
    }

    /// Returns the sender UID.
    pub fn sender_uid(&self) -> u32 {
        self.sender_uid
    }

    /// Returns the signal value.
    pub fn value(&self) -> u64 {
        self.value
    }
}

// ======================================================================
// Signal set
// ======================================================================

/// A bitmask of signals (sigset_t).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SigSet {
    /// Bitmask: bit N-1 corresponds to signal N.
    mask: u64,
}

impl SigSet {
    /// Creates an empty signal set.
    pub const fn empty() -> Self {
        Self { mask: 0 }
    }

    /// Creates a full signal set (all signals set).
    pub const fn full() -> Self {
        Self { mask: u64::MAX }
    }

    /// Creates a signal set from a raw bitmask.
    pub const fn from_mask(mask: u64) -> Self {
        Self { mask }
    }

    /// Returns the raw bitmask.
    pub fn mask(&self) -> u64 {
        self.mask
    }

    /// Adds a signal to the set.
    pub fn add(&mut self, signo: u8) {
        if signo >= 1 && signo <= NUM_SIGNALS as u8 {
            self.mask |= 1u64 << (signo - 1);
        }
    }

    /// Removes a signal from the set.
    pub fn del(&mut self, signo: u8) {
        if signo >= 1 && signo <= NUM_SIGNALS as u8 {
            self.mask &= !(1u64 << (signo - 1));
        }
    }

    /// Tests whether a signal is in the set.
    pub fn is_member(&self, signo: u8) -> bool {
        if signo >= 1 && signo <= NUM_SIGNALS as u8 {
            (self.mask & (1u64 << (signo - 1))) != 0
        } else {
            false
        }
    }

    /// Returns true if the set is empty.
    pub fn is_empty(&self) -> bool {
        self.mask == 0
    }

    /// Union with another set.
    pub fn union(&self, other: &SigSet) -> SigSet {
        SigSet {
            mask: self.mask | other.mask,
        }
    }

    /// Intersection with another set.
    pub fn intersect(&self, other: &SigSet) -> SigSet {
        SigSet {
            mask: self.mask & other.mask,
        }
    }

    /// Remove signals in `other` from this set.
    pub fn subtract(&self, other: &SigSet) -> SigSet {
        SigSet {
            mask: self.mask & !other.mask,
        }
    }

    /// Returns the lowest signal number set, or None.
    pub fn first_set(&self) -> Option<u8> {
        if self.mask == 0 {
            return None;
        }
        Some(self.mask.trailing_zeros() as u8 + 1)
    }

    /// Returns the number of signals in the set.
    pub fn count(&self) -> u32 {
        self.mask.count_ones()
    }
}

// ======================================================================
// Pending signal state
// ======================================================================

/// Pending signals for a task or thread group.
pub struct SigPending {
    /// Which signals are pending (bitmask).
    signal: SigSet,
    /// Queued signal info entries.
    queue: [SigQueueEntry; MAX_SIGQUEUE],
    /// Number of queued entries.
    queue_count: usize,
    /// Blocked signal mask.
    blocked: SigSet,
    /// Real blocked mask (saved during RT signal handler).
    real_blocked: SigSet,
    /// Saved signal mask (for sigsuspend).
    saved_sigmask: SigSet,
    /// Whether saved_sigmask is valid.
    restore_sigmask: bool,
}

impl SigPending {
    /// Creates a new empty pending signal state.
    pub const fn new() -> Self {
        Self {
            signal: SigSet::empty(),
            queue: [const { SigQueueEntry::new() }; MAX_SIGQUEUE],
            queue_count: 0,
            blocked: SigSet::empty(),
            real_blocked: SigSet::empty(),
            saved_sigmask: SigSet::empty(),
            restore_sigmask: false,
        }
    }

    /// Returns the pending signal set.
    pub fn pending_set(&self) -> &SigSet {
        &self.signal
    }

    /// Returns the blocked signal set.
    pub fn blocked(&self) -> &SigSet {
        &self.blocked
    }

    /// Sets the blocked signal mask.
    pub fn set_blocked(&mut self, mask: SigSet) {
        // Cannot block SIGKILL or SIGSTOP.
        self.blocked = SigSet::from_mask(mask.mask() & !UNCATCHABLE_MASK);
    }

    /// Returns the number of queued entries.
    pub fn queue_count(&self) -> usize {
        self.queue_count
    }

    /// Returns true if there are pending signals.
    pub fn signal_pending(&self) -> bool {
        !self.signal.is_empty()
    }

    /// Returns true if there are pending, unblocked signals.
    pub fn has_pending_signals(&self) -> bool {
        let unblocked = self.signal.subtract(&self.blocked);
        !unblocked.is_empty()
    }

    /// Sends a signal (adds to pending set and queue).
    pub fn send_signal(
        &mut self,
        signo: u8,
        code: SigCode,
        sender_pid: u32,
        sender_uid: u32,
        value: u64,
        timestamp_ns: u64,
    ) -> Result<()> {
        if signo == 0 || signo > NUM_SIGNALS as u8 {
            return Err(Error::InvalidArgument);
        }
        // Add to the pending set.
        self.signal.add(signo);
        // Queue the siginfo (best effort — standard signals can
        // coalesce).
        if let Some(slot) = self.queue.iter().position(|e| !e.occupied) {
            self.queue[slot] = SigQueueEntry {
                signo,
                code,
                sender_pid,
                sender_uid,
                value,
                timestamp_ns,
                occupied: true,
            };
            self.queue_count += 1;
        }
        // For standard signals (1-31), it's OK if queueing fails —
        // the bit in the signal set is sufficient.
        Ok(())
    }

    /// Dequeues the highest-priority pending, unblocked signal.
    ///
    /// Returns the dequeued entry if one was found.
    pub fn dequeue_signal(&mut self) -> Option<SigQueueEntry> {
        let unblocked = self.signal.subtract(&self.blocked);
        let signo = unblocked.first_set()?;
        // Find a matching queue entry.
        let mut found_idx = None;
        for i in 0..MAX_SIGQUEUE {
            if self.queue[i].occupied && self.queue[i].signo == signo {
                found_idx = Some(i);
                break;
            }
        }
        if let Some(idx) = found_idx {
            let entry = self.queue[idx];
            self.queue[idx].occupied = false;
            self.queue_count = self.queue_count.saturating_sub(1);
            // Check if there are more queued entries for this signal.
            let has_more = self.queue.iter().any(|e| e.occupied && e.signo == signo);
            if !has_more {
                self.signal.del(signo);
            }
            Some(entry)
        } else {
            // No queued entry but bit is set — create a synthetic
            // entry.
            self.signal.del(signo);
            Some(SigQueueEntry {
                signo,
                code: SigCode::Kernel,
                sender_pid: 0,
                sender_uid: 0,
                value: 0,
                timestamp_ns: 0,
                occupied: false,
            })
        }
    }

    /// Flushes all pending signals.
    pub fn flush_signals(&mut self) {
        self.signal = SigSet::empty();
        for entry in &mut self.queue {
            entry.occupied = false;
        }
        self.queue_count = 0;
    }

    /// Flushes a specific signal from pending and queue.
    pub fn flush_signal(&mut self, signo: u8) {
        self.signal.del(signo);
        for entry in &mut self.queue {
            if entry.occupied && entry.signo == signo {
                entry.occupied = false;
                self.queue_count = self.queue_count.saturating_sub(1);
            }
        }
    }

    /// Saves the current sigmask and sets a new one (for
    /// sigsuspend).
    pub fn save_and_set_blocked(&mut self, new_mask: SigSet) {
        self.saved_sigmask = self.blocked;
        self.restore_sigmask = true;
        self.set_blocked(new_mask);
    }

    /// Restores the saved sigmask.
    pub fn restore_blocked(&mut self) {
        if self.restore_sigmask {
            self.blocked = self.saved_sigmask;
            self.restore_sigmask = false;
        }
    }

    /// Returns whether a specific signal is pending.
    pub fn is_signal_pending(&self, signo: u8) -> bool {
        self.signal.is_member(signo)
    }

    /// Returns the next pending, unblocked signal number (without
    /// dequeuing).
    pub fn next_signal(&self) -> Option<u8> {
        let unblocked = self.signal.subtract(&self.blocked);
        unblocked.first_set()
    }
}
