// Copyright 2026 ONCRIX Contributors
// SPDX-License-Identifier: Apache-2.0

//! TCP Fast Open (TFO) extension for the ONCRIX network stack.
//!
//! Implements RFC 7413 TCP Fast Open, which allows data exchange
//! during the initial TCP handshake by using cryptographic cookies.
//! On a repeated connection to the same server, the client can send
//! application data in the SYN packet, reducing round-trip latency
//! from two RTTs (connect + first write) to one.
//!
//! # Cookie mechanism
//!
//! 1. The client sends a SYN with an empty TFO cookie option,
//!    requesting a cookie from the server.
//! 2. The server generates an 8-byte [`TfoCookie`] based on the
//!    client's IP address and a secret key, returning it in the
//!    SYN+ACK.
//! 3. On subsequent connections, the client includes the cookie
//!    (and optional data) in the SYN.
//! 4. The server validates the cookie and, if valid, immediately
//!    delivers the SYN data to the application.
//!
//! # Key structures
//!
//! | Type              | Purpose                                       |
//! |-------------------|-----------------------------------------------|
//! | [`TfoState`]      | Per-connection TFO negotiation state          |
//! | [`TfoCookie`]     | 8-byte opaque cookie value                    |
//! | [`TfoCookieJar`]  | Server-side cookie cache (64 entries)         |
//! | [`TfoConnection`] | TCP connection with TFO extensions            |
//! | [`TfoStats`]      | Global TFO statistics counters                |
//! | [`TfoRegistry`]   | Registry of TFO-enabled listening sockets     |

use oncrix_lib::{Error, Result};

// =========================================================================
// Constants
// =========================================================================

/// Size of a TFO cookie in bytes.
const TFO_COOKIE_LEN: usize = 8;

/// Maximum number of cached cookies in a [`TfoCookieJar`].
const TFO_COOKIE_JAR_SIZE: usize = 64;

/// Cookie expiry in ticks (approximately 5 minutes at 1 tick/s).
const TFO_COOKIE_EXPIRY_TICKS: u64 = 300;

/// Maximum data that may be carried in a SYN packet (bytes).
const TFO_MAX_SYN_DATA: usize = 1460;

/// Maximum number of TFO-enabled listening sockets.
const TFO_REGISTRY_SIZE: usize = 32;

/// Maximum number of bytes in the send buffer.
const SEND_BUF_SIZE: usize = 4096;

/// Maximum number of bytes in the receive buffer.
const RECV_BUF_SIZE: usize = 4096;

// =========================================================================
// TfoState
// =========================================================================

/// Per-connection TFO negotiation state.
///
/// Tracks the progression of the TCP Fast Open cookie exchange
/// between client and server during connection setup.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TfoState {
    /// TFO is disabled for this connection.
    Disabled,
    /// Client is requesting a cookie from the server (SYN with
    /// empty cookie option).
    Requesting,
    /// Server has accepted the TFO cookie; SYN data is being
    /// delivered to the application.
    Accepted,
    /// TFO handshake completed; connection is fully established
    /// with data already exchanged.
    Established,
}

// =========================================================================
// TfoCookie
// =========================================================================

/// An 8-byte TCP Fast Open cookie.
///
/// Generated by the server from the client's IP address and a
/// server-side secret key.  The cookie is opaque to the client.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct TfoCookie {
    /// Raw cookie bytes.
    bytes: [u8; TFO_COOKIE_LEN],
}

impl TfoCookie {
    /// Create a new cookie with the given bytes.
    pub const fn new(bytes: [u8; TFO_COOKIE_LEN]) -> Self {
        Self { bytes }
    }

    /// Return the raw cookie bytes.
    pub const fn as_bytes(&self) -> &[u8; TFO_COOKIE_LEN] {
        &self.bytes
    }

    /// Generate a TFO cookie from a client IP address and a secret key.
    ///
    /// Uses a simplified HMAC-like hash: the IP bytes and the secret key
    /// are mixed through repeated XOR and rotate operations to produce
    /// an 8-byte cookie.  This is not cryptographically strong but
    /// serves as a placeholder for a real HMAC-SipHash implementation.
    pub fn generate(client_ip: &[u8; 4], secret: &[u8; 16]) -> Self {
        let mut state: u64 = 0;

        // Mix the secret key into the state.
        let k0 = u64::from_le_bytes([
            secret[0], secret[1], secret[2], secret[3], secret[4], secret[5], secret[6], secret[7],
        ]);
        let k1 = u64::from_le_bytes([
            secret[8], secret[9], secret[10], secret[11], secret[12], secret[13], secret[14],
            secret[15],
        ]);
        state = state.wrapping_add(k0);
        state ^= k1;

        // Mix the client IP into the state.
        let ip_val = u32::from_be_bytes(*client_ip) as u64;
        state = state.wrapping_add(ip_val);
        state ^= state.rotate_left(13);
        state = state.wrapping_mul(0x5bd1_e995_5bd1_e995);
        state ^= state.rotate_right(7);

        Self {
            bytes: state.to_le_bytes(),
        }
    }

    /// Validate this cookie against a freshly computed one.
    ///
    /// Returns `true` if the cookies match and the stored timestamp
    /// is within [`TFO_COOKIE_EXPIRY_TICKS`] of `current_tick`.
    pub fn validate(&self, expected: &TfoCookie, stored_tick: u64, current_tick: u64) -> bool {
        if self.bytes != expected.bytes {
            return false;
        }
        let age = current_tick.saturating_sub(stored_tick);
        age <= TFO_COOKIE_EXPIRY_TICKS
    }
}

// =========================================================================
// TfoCookieEntry
// =========================================================================

/// A single entry in the server-side cookie jar.
#[derive(Debug, Clone, Copy)]
struct TfoCookieEntry {
    /// Client IPv4 address this cookie was issued for.
    client_ip: [u8; 4],
    /// The cookie value.
    cookie: TfoCookie,
    /// Tick at which this cookie was generated.
    created_tick: u64,
    /// Whether this slot is occupied.
    in_use: bool,
}

impl TfoCookieEntry {
    /// An empty, unused entry.
    const EMPTY: Self = Self {
        client_ip: [0; 4],
        cookie: TfoCookie::new([0; TFO_COOKIE_LEN]),
        created_tick: 0,
        in_use: false,
    };
}

// =========================================================================
// TfoCookieJar
// =========================================================================

/// Server-side cookie storage for TCP Fast Open.
///
/// Maintains up to [`TFO_COOKIE_JAR_SIZE`] (64) cookie entries,
/// indexed by client IP address.  The server secret key can be
/// rotated at any time; existing cookies remain valid until they
/// expire.
pub struct TfoCookieJar {
    /// Cookie entries.
    entries: [TfoCookieEntry; TFO_COOKIE_JAR_SIZE],
    /// Current server secret key (16 bytes).
    secret: [u8; 16],
    /// Previous server secret key for rotation grace period.
    prev_secret: [u8; 16],
    /// Tick at which the current secret was installed.
    secret_rotation_tick: u64,
}

impl Default for TfoCookieJar {
    fn default() -> Self {
        Self::new([0u8; 16])
    }
}

impl TfoCookieJar {
    /// Create a new cookie jar with the given initial secret key.
    pub const fn new(secret: [u8; 16]) -> Self {
        Self {
            entries: [TfoCookieEntry::EMPTY; TFO_COOKIE_JAR_SIZE],
            secret,
            prev_secret: [0u8; 16],
            secret_rotation_tick: 0,
        }
    }

    /// Rotate the server secret key.
    ///
    /// The previous key is retained so that cookies generated just
    /// before rotation remain valid for the remainder of their
    /// expiry window.
    pub fn rotate_secret(&mut self, new_secret: [u8; 16], current_tick: u64) {
        self.prev_secret = self.secret;
        self.secret = new_secret;
        self.secret_rotation_tick = current_tick;
    }

    /// Generate and store a cookie for the given client IP.
    ///
    /// If a cookie for this IP already exists, it is replaced.
    /// If the jar is full, the oldest entry is evicted.
    pub fn generate(&mut self, client_ip: &[u8; 4], current_tick: u64) -> TfoCookie {
        let cookie = TfoCookie::generate(client_ip, &self.secret);

        // Look for an existing entry for this IP, or the oldest entry.
        let mut target_idx = 0;
        let mut oldest_tick = u64::MAX;
        let mut found_existing = false;

        for i in 0..TFO_COOKIE_JAR_SIZE {
            if !self.entries[i].in_use {
                target_idx = i;
                break;
            }
            if self.entries[i].client_ip == *client_ip {
                target_idx = i;
                found_existing = true;
                break;
            }
            if self.entries[i].created_tick < oldest_tick {
                oldest_tick = self.entries[i].created_tick;
                target_idx = i;
            }
        }

        let _ = found_existing; // Suppress unused warning; kept for clarity.

        self.entries[target_idx] = TfoCookieEntry {
            client_ip: *client_ip,
            cookie,
            created_tick: current_tick,
            in_use: true,
        };

        cookie
    }

    /// Validate a cookie presented by a client.
    ///
    /// Looks up the stored cookie for the client IP and checks
    /// that the presented cookie matches and has not expired.
    /// Also tries re-generating with the previous secret key to
    /// handle the rotation grace period.
    pub fn validate(&self, client_ip: &[u8; 4], presented: &TfoCookie, current_tick: u64) -> bool {
        // Look up the stored entry for this client IP.
        for i in 0..TFO_COOKIE_JAR_SIZE {
            if !self.entries[i].in_use {
                continue;
            }
            if self.entries[i].client_ip != *client_ip {
                continue;
            }

            // First, try matching against the stored cookie directly.
            if presented.validate(
                &self.entries[i].cookie,
                self.entries[i].created_tick,
                current_tick,
            ) {
                return true;
            }

            // Try previous secret (rotation grace period):
            // regenerate what the cookie would have been under the
            // old key and compare.
            let expected_prev = TfoCookie::generate(client_ip, &self.prev_secret);
            if presented.validate(&expected_prev, self.entries[i].created_tick, current_tick) {
                return true;
            }

            return false;
        }
        false
    }

    /// Remove expired entries from the jar.
    pub fn evict_expired(&mut self, current_tick: u64) {
        for i in 0..TFO_COOKIE_JAR_SIZE {
            if !self.entries[i].in_use {
                continue;
            }
            let age = current_tick.saturating_sub(self.entries[i].created_tick);
            if age > TFO_COOKIE_EXPIRY_TICKS {
                self.entries[i].in_use = false;
            }
        }
    }
}

// =========================================================================
// TfoStats
// =========================================================================

/// Global TCP Fast Open statistics.
///
/// Tracks key metrics for monitoring TFO usage and diagnosing
/// cookie validation failures.
#[derive(Debug, Clone, Copy, Default)]
pub struct TfoStats {
    /// Number of SYN packets received with a TFO cookie option.
    pub requests_received: u64,
    /// Number of cookies successfully generated and issued.
    pub cookies_generated: u64,
    /// Number of presented cookies that passed validation.
    pub cookies_valid: u64,
    /// Number of presented cookies that were expired.
    pub cookies_expired: u64,
    /// Number of SYN packets that carried application data.
    pub data_in_syn_sent: u64,
}

impl TfoStats {
    /// Create a zeroed statistics block.
    pub const fn new() -> Self {
        Self {
            requests_received: 0,
            cookies_generated: 0,
            cookies_valid: 0,
            cookies_expired: 0,
            data_in_syn_sent: 0,
        }
    }

    /// Reset all counters to zero.
    pub fn reset(&mut self) {
        *self = Self::new();
    }
}

// =========================================================================
// TfoConnection
// =========================================================================

/// A TCP connection extended with TCP Fast Open state.
///
/// Wraps the core TCP connection fields and adds TFO-specific
/// cookie handling and SYN+data support.  When TFO is enabled,
/// the client may include application data in the SYN packet,
/// and the server may deliver that data before the handshake
/// completes.
pub struct TfoConnection {
    /// TFO negotiation state.
    pub tfo_state: TfoState,
    /// Cookie for this connection (client-side cache or
    /// server-side issued cookie).
    pub cookie: TfoCookie,
    /// Local port number.
    pub local_port: u16,
    /// Remote port number.
    pub remote_port: u16,
    /// Local IPv4 address.
    pub local_ip: [u8; 4],
    /// Remote IPv4 address.
    pub remote_ip: [u8; 4],
    /// SND.NXT — next sequence number to send.
    pub send_next: u32,
    /// SND.UNA — oldest unacknowledged sequence number.
    pub send_unack: u32,
    /// RCV.NXT — next expected sequence number from the remote.
    pub recv_next: u32,
    /// Outgoing data buffer.
    send_buf: [u8; SEND_BUF_SIZE],
    /// Number of valid bytes in `send_buf`.
    send_len: usize,
    /// Incoming data buffer.
    recv_buf: [u8; RECV_BUF_SIZE],
    /// Number of valid bytes in `recv_buf`.
    recv_len: usize,
    /// Whether this connection slot is in use.
    in_use: bool,
}

impl Default for TfoConnection {
    fn default() -> Self {
        Self::new()
    }
}

impl TfoConnection {
    /// Create a new TFO connection in the disabled state.
    pub const fn new() -> Self {
        Self {
            tfo_state: TfoState::Disabled,
            cookie: TfoCookie::new([0; TFO_COOKIE_LEN]),
            local_port: 0,
            remote_port: 0,
            local_ip: [0; 4],
            remote_ip: [0; 4],
            send_next: 0,
            send_unack: 0,
            recv_next: 0,
            send_buf: [0; SEND_BUF_SIZE],
            send_len: 0,
            recv_buf: [0; RECV_BUF_SIZE],
            recv_len: 0,
            in_use: false,
        }
    }

    /// Buffer incoming data from a SYN+data segment.
    ///
    /// Copies up to [`RECV_BUF_SIZE`] bytes of SYN payload into the
    /// receive buffer.  Returns the number of bytes buffered.
    fn buffer_syn_data(&mut self, data: &[u8]) -> usize {
        let available = RECV_BUF_SIZE.saturating_sub(self.recv_len);
        let limit = if data.len() < TFO_MAX_SYN_DATA {
            data.len()
        } else {
            TFO_MAX_SYN_DATA
        };
        let count = if limit < available { limit } else { available };
        if count > 0 {
            self.recv_buf[self.recv_len..self.recv_len + count].copy_from_slice(&data[..count]);
            self.recv_len += count;
        }
        count
    }

    /// Read received data from the receive buffer.
    ///
    /// Copies up to `buf.len()` bytes and shifts the remaining data
    /// forward.  Returns the number of bytes actually read.
    pub fn recv(&mut self, buf: &mut [u8]) -> usize {
        let count = if buf.len() < self.recv_len {
            buf.len()
        } else {
            self.recv_len
        };
        if count > 0 {
            buf[..count].copy_from_slice(&self.recv_buf[..count]);
            let remaining = self.recv_len - count;
            if remaining > 0 {
                let mut i = 0;
                while i < remaining {
                    self.recv_buf[i] = self.recv_buf[count + i];
                    i += 1;
                }
            }
            self.recv_len = remaining;
        }
        count
    }

    /// Buffer outgoing data for transmission.
    ///
    /// Returns the number of bytes actually buffered.
    pub fn send(&mut self, data: &[u8]) -> usize {
        let available = SEND_BUF_SIZE.saturating_sub(self.send_len);
        let count = if data.len() < available {
            data.len()
        } else {
            available
        };
        if count > 0 {
            self.send_buf[self.send_len..self.send_len + count].copy_from_slice(&data[..count]);
            self.send_len += count;
        }
        count
    }

    /// Return the number of bytes available to read.
    pub const fn recv_available(&self) -> usize {
        self.recv_len
    }
}

// =========================================================================
// TfoRegistryEntry
// =========================================================================

/// An entry in the TFO-enabled listening socket registry.
#[derive(Debug, Clone, Copy)]
struct TfoRegistryEntry {
    /// Listening port.
    port: u16,
    /// Whether TFO is enabled for this socket.
    enabled: bool,
    /// Whether this slot is in use.
    in_use: bool,
}

impl TfoRegistryEntry {
    /// An empty entry.
    const EMPTY: Self = Self {
        port: 0,
        enabled: false,
        in_use: false,
    };
}

// =========================================================================
// TfoRegistry
// =========================================================================

/// Registry of TFO-enabled listening sockets.
///
/// Tracks up to [`TFO_REGISTRY_SIZE`] (32) listening sockets that
/// have TFO enabled.  The kernel consults this registry when
/// processing incoming SYN packets that carry a TFO cookie.
pub struct TfoRegistry {
    /// Socket entries.
    entries: [TfoRegistryEntry; TFO_REGISTRY_SIZE],
    /// Global TFO statistics.
    pub stats: TfoStats,
    /// Server-side cookie jar.
    pub cookie_jar: TfoCookieJar,
}

impl Default for TfoRegistry {
    fn default() -> Self {
        Self::new([0u8; 16])
    }
}

impl TfoRegistry {
    /// Create a new registry with the given initial server secret.
    pub const fn new(secret: [u8; 16]) -> Self {
        Self {
            entries: [TfoRegistryEntry::EMPTY; TFO_REGISTRY_SIZE],
            stats: TfoStats::new(),
            cookie_jar: TfoCookieJar::new(secret),
        }
    }

    /// Enable TFO for a listening socket on the given port.
    ///
    /// # Errors
    ///
    /// Returns [`Error::AlreadyExists`] if TFO is already enabled
    /// on this port, or [`Error::OutOfMemory`] if the registry is
    /// full.
    pub fn enable(&mut self, port: u16) -> Result<()> {
        // Check for duplicates.
        for i in 0..TFO_REGISTRY_SIZE {
            if self.entries[i].in_use && self.entries[i].port == port {
                return Err(Error::AlreadyExists);
            }
        }
        // Find a free slot.
        for i in 0..TFO_REGISTRY_SIZE {
            if !self.entries[i].in_use {
                self.entries[i] = TfoRegistryEntry {
                    port,
                    enabled: true,
                    in_use: true,
                };
                return Ok(());
            }
        }
        Err(Error::OutOfMemory)
    }

    /// Disable TFO for a listening socket on the given port.
    ///
    /// # Errors
    ///
    /// Returns [`Error::NotFound`] if the port is not registered.
    pub fn disable(&mut self, port: u16) -> Result<()> {
        for i in 0..TFO_REGISTRY_SIZE {
            if self.entries[i].in_use && self.entries[i].port == port {
                self.entries[i].in_use = false;
                self.entries[i].enabled = false;
                return Ok(());
            }
        }
        Err(Error::NotFound)
    }

    /// Check whether TFO is enabled for the given port.
    pub fn is_enabled(&self, port: u16) -> bool {
        for i in 0..TFO_REGISTRY_SIZE {
            if self.entries[i].in_use && self.entries[i].port == port && self.entries[i].enabled {
                return true;
            }
        }
        false
    }
}

// =========================================================================
// Public API functions
// =========================================================================

/// Generate a TFO cookie for a client and record it in the jar.
///
/// Called by the server when a SYN is received with an empty TFO
/// cookie option (cookie request).  The generated cookie is
/// returned in the SYN+ACK.
///
/// # Errors
///
/// Returns [`Error::InvalidArgument`] if TFO is not enabled for
/// `server_port` in the given registry.
pub fn tfo_create_cookie(
    registry: &mut TfoRegistry,
    client_ip: &[u8; 4],
    server_port: u16,
    current_tick: u64,
) -> Result<TfoCookie> {
    if !registry.is_enabled(server_port) {
        return Err(Error::InvalidArgument);
    }
    registry.stats.requests_received += 1;
    let cookie = registry.cookie_jar.generate(client_ip, current_tick);
    registry.stats.cookies_generated += 1;
    Ok(cookie)
}

/// Validate a TFO cookie presented by a client.
///
/// Returns `true` if the cookie is valid and not expired.
/// Updates the registry statistics accordingly.
///
/// # Errors
///
/// Returns [`Error::InvalidArgument`] if TFO is not enabled for
/// `server_port`.
pub fn tfo_validate_cookie(
    registry: &mut TfoRegistry,
    client_ip: &[u8; 4],
    server_port: u16,
    presented: &TfoCookie,
    current_tick: u64,
) -> Result<bool> {
    if !registry.is_enabled(server_port) {
        return Err(Error::InvalidArgument);
    }
    registry.stats.requests_received += 1;

    let valid = registry
        .cookie_jar
        .validate(client_ip, presented, current_tick);
    if valid {
        registry.stats.cookies_valid += 1;
    } else {
        registry.stats.cookies_expired += 1;
    }
    Ok(valid)
}

/// Handle an incoming SYN that carries data (TFO fast path).
///
/// If the cookie is valid, the SYN data is buffered into the
/// connection's receive buffer and the connection transitions to
/// [`TfoState::Accepted`].  The caller should then complete the
/// handshake and deliver the data to the application.
///
/// # Errors
///
/// Returns [`Error::InvalidArgument`] if:
/// - TFO is not enabled for `server_port`.
/// - `syn_data` is empty (no data in SYN).
/// - The cookie validation fails.
pub fn tfo_handle_syn_data(
    registry: &mut TfoRegistry,
    conn: &mut TfoConnection,
    client_ip: &[u8; 4],
    server_port: u16,
    presented: &TfoCookie,
    syn_data: &[u8],
    current_tick: u64,
) -> Result<usize> {
    if syn_data.is_empty() {
        return Err(Error::InvalidArgument);
    }
    let valid = tfo_validate_cookie(registry, client_ip, server_port, presented, current_tick)?;
    if !valid {
        return Err(Error::InvalidArgument);
    }

    registry.stats.data_in_syn_sent += 1;

    conn.remote_ip = *client_ip;
    conn.local_port = server_port;
    conn.tfo_state = TfoState::Accepted;
    conn.in_use = true;

    let buffered = conn.buffer_syn_data(syn_data);
    conn.recv_next = conn.recv_next.wrapping_add(buffered as u32);

    Ok(buffered)
}

/// Initiate a TFO-enabled connection from the client side.
///
/// If the client has a cached cookie for the server, it may
/// include up to [`TFO_MAX_SYN_DATA`] bytes of application data
/// in the SYN.  The connection transitions to
/// [`TfoState::Requesting`] (no cookie) or
/// [`TfoState::Established`] (with cookie + data).
///
/// Returns the number of data bytes that will be included in the
/// SYN packet.
///
/// # Errors
///
/// Returns [`Error::InvalidArgument`] if the connection is already
/// in use.
pub fn tfo_connect_with_cookie(
    conn: &mut TfoConnection,
    server_ip: [u8; 4],
    server_port: u16,
    cookie: Option<&TfoCookie>,
    data: &[u8],
) -> Result<usize> {
    if conn.in_use {
        return Err(Error::InvalidArgument);
    }

    conn.remote_ip = server_ip;
    conn.remote_port = server_port;
    conn.in_use = true;

    match cookie {
        Some(c) => {
            conn.cookie = *c;
            let sent = conn.send(data);
            conn.tfo_state = TfoState::Established;
            Ok(sent)
        }
        None => {
            // No cookie — request one from the server.
            conn.tfo_state = TfoState::Requesting;
            Ok(0)
        }
    }
}
