[package]
name = "oncrix-cksum"
description = "ONCRIX - /bin/cksum utility"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[[bin]]
name = "cksum"
path = "src/main.rs"

[dependencies]
oncrix-ulibc.workspace = true
