[package]
name = "oncrix-ifconfig"
description = "ONCRIX - /bin/ifconfig utility"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[[bin]]
name = "ifconfig"
path = "src/main.rs"

[dependencies]
oncrix-ulibc.workspace = true
