[package]
name = "oncrix-truncate"
description = "ONCRIX - /bin/truncate utility"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[[bin]]
name = "truncate"
path = "src/main.rs"

[dependencies]
oncrix-ulibc.workspace = true
